In [6]:
import pandas as pd

In [127]:
def create_clean_df_for_Content_pipeline(movies_df,tags_df):
    new_movies_df = movies_df[['movieId','title','genres']].copy()
    # cleaning movies_df
    new_movies_df['title'] = (
        movies_df['title'].fillna("")
        .astype(str)
        .str.strip()
    )
    new_movies_df['genres'] = (
        new_movies_df['genres'].fillna("")
        .astype(str)
        .str.replace("|"," ")
        .str.strip()
    )
    
    # cleaning tags_df
    new_tags_df = tags_df[["movieId","tag"]].copy()
    new_tags_df.dropna(subset=['movieId','tag'])
    
    new_tags_df['tag'] = (
    new_tags_df['tag']
    .astype(str)
    .str.strip()
    .str.lower()
    )
    
    new_tags_df = new_tags_df[new_tags_df['tag'] != ""]
    
    tags_grouped = (
    new_tags_df.groupby('movieId')['tag']
    .apply(lambda crr_mov_tags : " ".join(crr_mov_tags)) # this lambda function input tags of first movie and join them with " " and then moves to next movie tags and do same upto so on
    .reset_index(name='tags') # it cut out the movieId from the resultant series into separate column and the name="tags" changes the name of remaining tag  series to tagss
)
    
    # merging the tags and movies_df
    movies_df_final = pd.merge(
        new_movies_df,
        tags_grouped,
        on='movieId',
        how='left',
        validate='one_to_one' # validating so that each movieId appears one in both data frames otherwise it will raise error 
    )
    
    # cleaning final frame 
    movies_df_final["tags"] = movies_df_final['tags'].fillna("")
    movies_df_final = movies_df_final.drop_duplicates(subset=["movieId"])
    movies_df_final = movies_df_final.reset_index(drop=True)
    
    return movies_df_final

In [73]:
movies = pd.read_csv(r'../datasets/movies.csv')
tags = pd.read_csv(r"../datasets/tags.csv")
tmdb = pd.read_csv(r'../datasets/tmdb_movies.csv')
ratings = pd.read_csv(r'../datasets/ratings.csv')

# Cleaning Tmdb dataframe

In [41]:
tmdb

,movieId,tmdbId,overview,release_date,poster_path,backdrop_path
0,1,862,"Led by Woody, Andy's toys live happily in his ...",1995-11-22,/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg,/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg
1,2,8844,When siblings Judy and Peter discover an encha...,1995-12-15,/bdHG5Mo83VPobeZZdlSz0Y7HQHB.jpg,/qSxeCfWUUyht9hZgaaYmtPtTkw2.jpg
2,3,15602,A family wedding reignites the ancient feud be...,1995-12-22,/1FSXpj5e8l4KH6nVFO5SPUeraOt.jpg,/1o4vuCHpmd4DXofMYDUwpnhKiuy.jpg
3,4,31357,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,/4wjGMwPsdlvi025ZqR4rXnFDvBz.jpg,/jZjoEKXMTDoZAGdkjhAdJaKtXSN.jpg
4,5,11862,Just when George Banks has recovered from his ...,1995-12-08,/rj4LBtwQ0uGrpBnCELr716Qo3mw.jpg,/lEsjVrGU21BeJjF5AF9EWsihDpw.jpg
...,...,...,...,...,...,...
9615,193581,432131,"Ciel learns of a ""Aurora Society"", that is rum...",2017-01-21,/4jU2Bdk1MB2OvP4BBvTJIPQc0BF.jpg,/clFQR5zwzDrayMVVe7axo0YLFfh.jpg
9616,193583,445030,Six thousand years before Sora and Shiro were ...,2017-07-15,/cCBB6BGRj5nCTaEgogDtkHfjOLK.jpg,/zmJtqKaByFqYrxipeXyoAUSTD1w.jpg
9617,193585,479308,A woman deals with the toxic water scandal in ...,2017-10-28,/iPzkjNWpK7ud5pE997eGaB4QhaG.jpg,/tcM6XoTYKATJyNTIuGPk4yh0g6N.jpg
9618,193587,483455,A large scale catastrophe is occurring across ...,2018-03-03,/gCfN6xWPyxphtgtLuDxT5s0eSoq.jpg,/vjnS4iu0SdwXm2LLqZGNCfpId9t.jpg
9619,193609,37891,"Outrageous, misogynistic and vulgar-to-the-max...",1991-05-17,/yXmkQVETaCr8BHITkLeJe6x1GdA.jpg,NaN

In [ ]:
# droping rows that have duplicate or None values 
tmdb.drop_duplicates(subset=["movieId"],inplace=True)
tmdb.drop_duplicates(subset=["overview"],inplace=True)
tmdb.drop_duplicates(subset=["poster_path"],inplace=True)
tmdb.drop_duplicates(subset=["backdrop_path"],inplace=True)
tmdb.drop_duplicates(subset=["movieId"],inplace=True)
tmdb.dropna(subset=["backdrop_path"],inplace=True)

In [124]:
tmdb_for_merge = tmdb[["movieId","overview"]] .copy()

# cleaning ratings data frame to get top popular movies

In [76]:
# Getting number of ratings applied to each movie and avg_rating applied to each movie by users
popular_movies = ratings.groupby('movieId').agg(
    num_ratings = ('rating','count'),
    avg_rating = ('rating','mean')
).reset_index().copy()

In [92]:
merged_pop_mov = pd.merge(popular_movies,movies,on="movieId",how="inner")

In [93]:
merged_pop_mov

,movieId,num_ratings,avg_rating,title,genres,year,imdbId,tmdbId
0,1,215,3.920930,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1995,114709,862
1,2,110,3.431818,Jumanji (1995),Adventure|Children|Fantasy,1995,113497,8844
2,3,52,3.259615,Grumpier Old Men (1995),Comedy|Romance,1995,113228,15602
3,4,7,2.357143,Waiting to Exhale (1995),Comedy|Drama|Romance,1995,114885,31357
4,5,49,3.071429,Father of the Bride Part II (1995),Comedy,1995,113041,11862
...,...,...,...,...,...,...,...,...
9699,193581,1,4.000000,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,2017,5476944,432131
9700,193583,1,3.500000,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,2017,5914996,445030
9701,193585,1,3.500000,Flint (2017),Drama,2017,6397426,479308
9702,193587,1,3.500000,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,2018,8391976,483455
9703,193609,1,4.000000,Andrew Dice Clay: Dice Rules (1991),Comedy,1991,101726,37891

In [108]:
new_popular_movies = merged_pop_mov.query('num_ratings>90 and year>1998 and avg_rating>2.8').copy()

In [109]:
new_popular_movies

,movieId,num_ratings,avg_rating,title,genres,year,imdbId,tmdbId
1880,2502,94,4.090426,Office Space (1999),Comedy|Crime,1999,151804,1542
1936,2571,278,4.192446,"Matrix, The (1999)",Action|Sci-Fi|Thriller,1999,133093,603
1976,2628,140,3.107143,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Sci-Fi,1999,120915,1893
2011,2683,121,3.198347,Austin Powers: The Spy Who Shagged Me (1999),Action|Adventure|Comedy,1999,145660,817
2028,2706,103,3.378641,American Pie (1999),Comedy|Romance,1999,163651,2105
2075,2762,179,3.893855,"Sixth Sense, The (1999)",Drama|Horror|Mystery,1999,167404,745
2141,2858,204,4.056373,American Beauty (1999),Drama|Romance,1999,169547,14
2221,2959,218,4.272936,Fight Club (1999),Action|Crime|Drama|Thriller,1999,137523,550
2254,2997,99,3.954545,Being John Malkovich (1999),Comedy|Drama|Fantasy,1999,120601,492
2350,3114,97,3.860825,Toy Story 2 (1999),Adventure|Animation|Children|Comedy|Fantasy,1999,120363,863
2367,3147,111,4.148649,"Green Mile, The (1999)",Crime|Drama,1999,120689,497
2667,3578,170,3.938235,Gladiator (2000),Action|Adventure|Drama,2000,172495,98
2829,3793,133,3.699248,X-Men (2000),Action|Adventure|Sci-Fi,2000,120903,36657
2937,3948,91,3.417582,Meet the Parents (2000),Comedy,2000,212338,1597
2938,3949,96,3.921875,Requiem for a Dream (2000),Drama,2000,180093,641
2976,3996,110,3.836364,"Crouching Tiger, Hidden Dragon (Wo hu cang lon...",Action|Drama|Romance,2000,190332,146
2989,4011,93,4.155914,Snatch (2000),Comedy|Crime|Thriller,2000,208092,107
2999,4022,100,3.700000,Cast Away (2000),Drama,2000,162222,8358
3003,4027,94,3.808511,"O Brother, Where Art Thou? (2000)",Adventure|Comedy|Crime,2000,190590,134
3132,4226,159,4.122642,Memento (2000),Mystery|Thriller,2000,209144,77
3185,4306,170,3.867647,Shrek (2001),Adventure|Animation|Children|Comedy|Fantasy|Ro...,2001,126029,808
3553,4878,109,3.981651,Donnie Darko (2001),Drama|Mystery|Sci-Fi|Thriller,2001,246578,141
3559,4886,132,3.871212,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy,2001,198781,585
3565,4896,107,3.761682,Harry Potter and the Sorcerer's Stone (a.k.a. ...,Adventure|Children|Fantasy,2001,241527,671
3605,4963,119,3.844538,Ocean's Eleven (2001),Crime|Thriller,2001,240772,161
3613,4973,120,4.183333,"Amelie (Fabuleux destin d'Amélie Poulain, Le) ...",Comedy|Romance,2001,211915,194
3629,4993,198,4.106061,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy,2001,120737,120
3631,4995,123,4.000000,"Beautiful Mind, A (2001)",Drama|Romance,2001,268978,453
3810,5349,122,3.540984,Spider-Man (2002),Action|Adventure|Sci-Fi|Thriller,2002,145487,557
3823,5378,92,3.157609,Star Wars: Episode II - Attack of the Clones (...,Action|Adventure|Sci-Fi|IMAX,2002,121765,1894
3845,5418,112,3.816964,"Bourne Identity, The (2002)",Action|Mystery|Thriller,2002,258463,2501
3864,5445,120,3.637500,Minority Report (2002),Action|Crime|Mystery|Sci-Fi|Thriller,2002,181689,180
4066,5816,102,3.598039,Harry Potter and the Chamber of Secrets (2002),Adventure|Fantasy,2002,295297,672
4127,5952,188,4.021277,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy,2002,167261,121
4149,5989,115,3.921739,Catch Me If You Can (2002),Crime|Drama,2002,264464,640
4341,6365,96,3.354167,"Matrix Reloaded, The (2003)",Action|Adventure|Sci-Fi|Thriller|IMAX,2003,234215,604
4350,6377,141,3.960993,Finding Nemo (2003),Adventure|Animation|Children|Comedy,2003,266543,12
4417,6539,149,3.778523,Pirates of the Caribbean: The Curse of the Bla...,Action|Adventure|Comedy|Fantasy,2003,325980,22
4603,6874,131,3.961832,Kill Bill: Vol. 1 (2003),Action|Crime|Thriller,2003,266697,24
4787,7153,185,4.118919,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy,2003,167260,122
4896,7361,131,4.160305,Eternal Sunshine of the Spotless Mind (2004),Drama|Romance|Sci-Fi,2004,338013,38
4922,7438,110,3.868182,Kill Bill: Vol. 2 (2004),Action|Drama|Thriller,2004,378194,393
5146,8360,92,3.576087,Shrek 2 (2004),Adventure|Animation|Children|Comedy|Musical|Ro...,2004,298148,809
5152,8368,93,3.913978,Harry Potter and the Prisoner of Azkaban (2004),Adventure|Fantasy|IMAX,2004,304141,673
5359,8961,125,3.836000,"Incredibles, The (2004)",Action|Adventure|Animation|Children|Comedy,2004,317705,9806
5895,33794,116,3.862069,Batman Begins (2005),Action|Crime|IMAX,2005,372784,272
6127,44191,100,3.885000,V for Vendetta (2006),Action|Sci-Fi|Thriller|IMAX,2006,434409,752
6291,48516,107,4.252336,"Departed, The (2006)",Crime|Drama|Thriller,2006,407887,1422
6686,58559,149,4.238255,"Dark Knight, The (2008)",Action|Crime|Drama|IMAX,2008,468569,155
6719,59315,94,3.824468,Iron Man (2008),Action|Adventure|Sci-Fi,2008,371746,1726
6748,60069,104,4.057692,WALL·E (2008),Adventure|Animation|Children|Romance|Sci-Fi,2008,910970,10681
7015,68954,105,4.004762,Up (2009),Adventure|Animation|Children|Drama,2009,1049413,14160
7188,72998,97,3.603093,Avatar (2009),Action|Adventure|Sci-Fi|IMAX,2009,499549,19995
7348,79132,143,4.066434,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX,2010,1375666,27205

In [110]:
new_popular_movies.drop(columns=['tmdbId'],inplace=True)

In [116]:
final_popular_df = pd.merge(new_popular_movies,tmdb,on='movieId',how="left")

In [117]:
final_popular_df.drop(columns=['tmdbId','year'],inplace=True)

In [120]:
final_popular_df.to_csv('../datasets/new_data_sets/top_movies.csv')

# merging cleaned merged tags and movies data frame with tmdbId frame

In [128]:
new_df = create_clean_df_for_Content_pipeline(movies,tags)

In [134]:
new_df

,movieId,title,genres,tags
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,pixar pixar fun
1,2,Jumanji (1995),Adventure Children Fantasy,fantasy magic board game robin williams game
2,3,Grumpier Old Men (1995),Comedy Romance,moldy old
3,4,Waiting to Exhale (1995),Comedy Drama Romance,
4,5,Father of the Bride Part II (1995),Comedy,pregnancy remake
...,...,...,...,...
9717,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy,
9718,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy,
9719,193585,Flint (2017),Drama,
9720,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation,
9721,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,

In [132]:
content_filt_df = pd.merge(new_df,tmdb_for_merge,on='movieId',how='inner')

In [142]:
content_filt_df.dropna(subset=['overview'],inplace=True)

In [145]:
content_filt_df

,movieId,title,genres,tags,overview
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,pixar pixar fun,"Led by Woody, Andy's toys live happily in his ..."
1,2,Jumanji (1995),Adventure Children Fantasy,fantasy magic board game robin williams game,When siblings Judy and Peter discover an encha...
2,3,Grumpier Old Men (1995),Comedy Romance,moldy old,A family wedding reignites the ancient feud be...
3,4,Waiting to Exhale (1995),Comedy Drama Romance,,"Cheated on, mistreated and stepped on, the wom..."
4,5,Father of the Bride Part II (1995),Comedy,pregnancy remake,Just when George Banks has recovered from his ...
...,...,...,...,...,...
9607,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy,,"Ciel learns of a ""Aurora Society"", that is rum..."
9608,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy,,Six thousand years before Sora and Shiro were ...
9609,193585,Flint (2017),Drama,,A woman deals with the toxic water scandal in ...
9610,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation,,A large scale catastrophe is occurring across ...
9611,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,,"Outrageous, misogynistic and vulgar-to-the-max..."

In [ ]:
content_filt_df['content'] = (
    content_filt_df['title']+" "
    +content_filt_df['genres'] + " "
    +content_filt_df['tags'] + " "
    + content_filt_df['overview']
).str.strip()

In [150]:
content_filt_df

,movieId,title,genres,tags,overview,content
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,pixar pixar fun,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995) Adventure Animation Children ...
1,2,Jumanji (1995),Adventure Children Fantasy,fantasy magic board game robin williams game,When siblings Judy and Peter discover an encha...,Jumanji (1995) Adventure Children Fantasy fant...
2,3,Grumpier Old Men (1995),Comedy Romance,moldy old,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995) Comedy Romance moldy o...
3,4,Waiting to Exhale (1995),Comedy Drama Romance,,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995) Comedy Drama Romance ...
4,5,Father of the Bride Part II (1995),Comedy,pregnancy remake,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995) Comedy preg...
...,...,...,...,...,...,...
9607,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy,,"Ciel learns of a ""Aurora Society"", that is rum...",Black Butler: Book of the Atlantic (2017) Acti...
9608,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy,,Six thousand years before Sora and Shiro were ...,No Game No Life: Zero (2017) Animation Comedy ...
9609,193585,Flint (2017),Drama,,A woman deals with the toxic water scandal in ...,Flint (2017) Drama A woman deals with the tox...
9610,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation,,A large scale catastrophe is occurring across ...,Bungo Stray Dogs: Dead Apple (2018) Action Ani...
9611,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,,"Outrageous, misogynistic and vulgar-to-the-max...",Andrew Dice Clay: Dice Rules (1991) Comedy Ou...

In [166]:
content_filt_df.to_csv('../datasets/new_data_sets/frame_of_colab_filt.csv')

## preparing a full movie info data set so that I use it to display information on website

In [153]:
movies.isnull().sum()

movieId    0
title      0
genres     0
year       0
imdbId     0
tmdbId     0
dtype: int64

In [161]:
info_frame = pd.merge(movies,tmdb,on='movieId',how='left')

In [164]:
final_info_df = info_frame.drop(columns=['year','tmdbId_x','tmdbId_y',]).copy()

In [163]:
final_info_df

,movieId,title,genres,imdbId,overview,release_date,poster_path,backdrop_path
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,114709,"Led by Woody, Andy's toys live happily in his ...",1995-11-22,/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg,/3Rfvhy1Nl6sSGJwyjb0QiZzZYlB.jpg
1,2,Jumanji (1995),Adventure|Children|Fantasy,113497,When siblings Judy and Peter discover an encha...,1995-12-15,/bdHG5Mo83VPobeZZdlSz0Y7HQHB.jpg,/qSxeCfWUUyht9hZgaaYmtPtTkw2.jpg
2,3,Grumpier Old Men (1995),Comedy|Romance,113228,A family wedding reignites the ancient feud be...,1995-12-22,/1FSXpj5e8l4KH6nVFO5SPUeraOt.jpg,/1o4vuCHpmd4DXofMYDUwpnhKiuy.jpg
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,114885,"Cheated on, mistreated and stepped on, the wom...",1995-12-22,/4wjGMwPsdlvi025ZqR4rXnFDvBz.jpg,/jZjoEKXMTDoZAGdkjhAdJaKtXSN.jpg
4,5,Father of the Bride Part II (1995),Comedy,113041,Just when George Banks has recovered from his ...,1995-12-08,/rj4LBtwQ0uGrpBnCELr716Qo3mw.jpg,/lEsjVrGU21BeJjF5AF9EWsihDpw.jpg
...,...,...,...,...,...,...,...,...
9717,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,5476944,"Ciel learns of a ""Aurora Society"", that is rum...",2017-01-21,/4jU2Bdk1MB2OvP4BBvTJIPQc0BF.jpg,/clFQR5zwzDrayMVVe7axo0YLFfh.jpg
9718,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,5914996,Six thousand years before Sora and Shiro were ...,2017-07-15,/cCBB6BGRj5nCTaEgogDtkHfjOLK.jpg,/zmJtqKaByFqYrxipeXyoAUSTD1w.jpg
9719,193585,Flint (2017),Drama,6397426,A woman deals with the toxic water scandal in ...,2017-10-28,/iPzkjNWpK7ud5pE997eGaB4QhaG.jpg,/tcM6XoTYKATJyNTIuGPk4yh0g6N.jpg
9720,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,8391976,A large scale catastrophe is occurring across ...,2018-03-03,/gCfN6xWPyxphtgtLuDxT5s0eSoq.jpg,/vjnS4iu0SdwXm2LLqZGNCfpId9t.jpg
9721,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,101726,"Outrageous, misogynistic and vulgar-to-the-max...",1991-05-17,/yXmkQVETaCr8BHITkLeJe6x1GdA.jpg,NaN

In [165]:
final_info_df.to_csv('../datasets/new_data_sets/movie_info.csv')